Repository FirelyTeam/firely-net-sdk, pull requests merged in 2019-10, with the labels that each got.

#1118 fix: #1116 initialize [...].extension.url fixed value, if missing
  src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
  src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
Labels: enhancement

#1117 fix: #1116 initialize [...].extension.url fixed value, if missing
  src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
  src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
Labels: enhancement

#1127 fix: #1123 ElementDefinition.base empty for contentReference children
  src/Hl7.Fhir.Specification.Tests/Snapshot/SnapshotGeneratorTest.cs
  src/Hl7.Fhir.Specification/Specification/Snapshot/SnapshotGenerator.cs
Labels: bug

#1115 Clarify that the data should be converted to DateTimeOffset instead
  src/Hl7.Fhir.Core/Support/DateExtensions.cs
Labels: bitesize!
